repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=100000"]  # Set limit to 100 MB
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    -   id: black

# For now pre-commit hooks to be run manually
# $ pre-commit run --all-files
