name: FraudDetection
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - pip
  - pandas
  - matplotlib
  - numpy
  - scikit-learn
  - lightgbm
  - seaborn
  - pyYAML
  - pip:
      - kaggle
      - ipykernel
      - pre-commit
      - pytest
      - dalex
      - kaleido
