name: FODS_coursework
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.12
  - pip
  - pandas
  - matplotlib
  - numpy
  - scikit-learn
  - lightgbm
  - pip:
      - kaggle
      - ipykernel
      - pre-commit
